INSERT INTO CATEGORY VALUES (ID, DESCRIPTION) VALUES (1, 'Comic Books');
INSERT INTO CATEGORY VALUES (ID, DESCRIPTION) VALUES (2, 'Movies');
INSERT INTO CATEGORY VALUES (ID, DESCRIPTION) VALUES (3, 'Books');

INSERT INTO SUPPLIER VALUES (ID, DESCRIPTION) VALUES (1, 'Panini Comics');
INSERT INTO SUPPLIER VALUES (ID, DESCRIPTION) VALUES (2, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (1, 'Crise nas Infinitas Terras', 1, 1, 10);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (2, 'Interestelar', 2, 2, 5);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES (3, 'Harry Potter E A Pedra Filosofal', 2, 3, 3);